### ISSUE TITLE
Can't convert frame to index; frame is too far in the past

### ISSUE THREAD

**Issue by hunter8288** [elementbound/unity-multiplayer-test#2]
Hello. I would like to inform you that this project works well for me only in the editor, but if I build the project, connect Clumsy, then both the client and the server stop working. Throws an exception at TickHistoryBuffer IndexOutOfRangeException($"Can't convert frame {frame} to index; frame is too far in the past"); 
Can this be fixed somehow? Unfortunately, I still don't understand what the problem is.
Thanks.

**Comment by elementbound** [comment]
Hey @hunter8288, thanks for checking out netwind! I haven't worked on this one in a while ( I have a different solution in the works ), but iirc this can happen at the start of the game for a bit and then be OK, as the history gets filled in ( for example if the game has been going on for 3 ticks, you can't rewind 4 ). 

Do you have a Unity project or something I can try and reproduce this with?

**Comment by hunter8288** [comment]
Thanks for reply. Please forgive me for distracting you. It seems that the problem is not in your code, but in the transport ([WebSocket](https://github.com/Unity-Technologies/multiplayer-community-contributions/tree/main/Transports/com.community.netcode.transport.websocket)) that I connected. I analyzed the project code for several days, trying to understand the cause of the error, but the problem was not where I was looking for. I'm ashamed, sorry again.

**Comment by elementbound** [comment]
Hey @hunter8288, no worries! I'm glad this issue was solved, and thank you for checkint out Netwind! Please feel free to open an issue if you run into further issues! :)
